# Generated by Django 4.0.1 on 2022-01-13 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_remove_band_active_band_year_formed'),
    ]

    operations = [
        migrations.AddField(
            model_name='band',
            name='publication_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
