# Generated by Django 4.0.1 on 2022-01-13 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_band_publication_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='band',
            name='biography',
        ),
        migrations.RemoveField(
            model_name='band',
            name='official_homepage',
        ),
        migrations.RemoveField(
            model_name='band',
            name='year_formed',
        ),
        migrations.AddField(
            model_name='band',
            name='channel',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='band',
            name='creator',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='band',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='band',
            name='genre',
            field=models.CharField(choices=[('AMV', 'Anime Music Vid'), ('GMV', 'Game Music Vid'), ('ASMV', 'Anime Sound Music Video')], max_length=5),
        ),
    ]
